---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy Nginx site config
  template:
    src: epicbook.conf.j2
    dest: /etc/nginx/sites-available/epicbook
    owner: www-data
    group: www-data
    mode: '0755'
  notify: Restart Nginx

- name: Enable epicbook site
  file:
    src: /etc/nginx/sites-available/epicbook
    dest: /etc/nginx/sites-enabled/epicbook
    state: link
    force: yes
  notify: Restart Nginx

- name: Remove default Nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: Restart Nginx

- name: Ensure nginx is started and enabled
  service:
    name: nginx
    state: started
    enabled: yes